Let know contributors they can add their login in contributors.txt
Avaiga/taipy-config pull request #53
Opened 2023-03-02 08:00 UTC by jrobinAV

https://github.com/Avaiga/taipy-doc/issues/386

If it s fine and approved, I will propagate the change in all our repos.

2023-03-20 10:18 UTC, jrobinAV commented
@FabienLelaquais Gentle reminder.

2023-03-20 12:13 UTC, FabienLelaquais requested changes
What do you think?

2023-03-20 12:13 UTC, FabienLelaquais commented on CONTRIBUTING.md
> +4. Make the change. You can also add your GitHub login in a new line of the `contributors.txt` file. We are using
=>
4. Make the changes.&lt;br/&gt;
&nbsp;&nbsp;&nbsp;You may want to also add your GitHub login as a new line of the \`contributors.txt\` file located at the root
&nbsp;&nbsp;&nbsp;of this repository. We are using it to list our contributors in the Taipy documentation (see the "Contributing > Contributors" section) and thank them.

2023-03-20 12:13 UTC, FabienLelaquais commented on CONTRIBUTING.md
> +5. Create a [pull request from your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
Add "&lt;br/&gt;" to actually break the line.

2023-03-20 12:13 UTC, FabienLelaquais commented on CONTRIBUTING.md
>     Keep your pull request in __draft__ until your work is finished.
request in \_\_draft\_\_ => request as \_\_draft\_\_

2023-03-20 12:13 UTC, FabienLelaquais commented on CONTRIBUTING.md
>     Before you submit a pull request read to review from your forked repo, check that it meets these guidelines:
"Before you submit a pull request read to review"
Not sure this is English. Is it?

2023-03-21 09:04 UTC, FabienLelaquais approved these changes
👌

2023-03-21 10:22 UTC, merged