Feature/Core - Add `Config._check_one()` method to run one checker at a time
Avaiga/taipy-config pull request #56
Opened 2023-03-17 10:45 UTC by trgiangdo

Used in https://github.com/Avaiga/taipy-core/pull/492 to run only the `_MigrationChecker` on production.

2023-03-17 11:06 UTC, trgiangdo commented on src/taipy/config/config.py
> +    def _check_one(cls, checker: Type[_ConfigChecker]) -> IssueCollector:
The naming is not perfect yet. Let me know what you think

2023-03-21 08:49 UTC, jrobinAV reviewed
I would not change the checker APIs just for a special case in particular because the case consists in checking a core section defined in the Core repository and code.

I believe we should not merge the PR.

2023-03-21 08:49 UTC, jrobinAV commented on src/taipy/config/config.py
> +    def _check_one(cls, checker: Type[_ConfigChecker]) -> IssueCollector:
We are exposing an API just for a special case, in order to run one checker that is defined in a 'user' repository (taipy-core in our case). 

I believe we should not do that.

2023-03-21 08:49 UTC, jrobinAV requested changes
I would not change the checker APIs just for a special case in particular because the case consists in checking a core section defined in the Core repository and code.

I believe we should not merge the PR.

2023-03-21 14:51 UTC, trgiangdo commented
In the latest commit, the `Config._check_one()` is removed.

To handle a separate checker on Core, the `Config.__log_message()` is removed, and we log the message when an Issue is added to the Collector.

2023-03-21 16:25 UTC, jrobinAV reviewed
I don't really like mixing the responsibilities of checking errors and logging them. I prefer to let the responsibility to the client for logging the messages.
For example, we can imagine a client not logging all issues. It may want to group them by type (or severity or whatever), and only log one issue per group and display the size of the group. This is pretty common, especially when there are a lot of issues.

Plus, I don't see any added value for the user.
The only difference I can see is really minor to me. It s just we don't need to log the migrationConfig issues in Core. Which I believe it s the right place.

I would personally just drop the PR. Sorry. What do you think? Do I miss a reason for such a change?

2023-03-21 16:35 UTC, trgiangdo commented
You're right. I'll close the PR and move the log method to core for the MigrationConfigChecker.

Thank you for the review

2023-03-21 16:35 UTC, closed without merging