Default and python configs updated at compilation
Avaiga/taipy-config pull request #70
Opened 2023-05-28 21:02 UTC by bobbyshermi

Fix issue: https://github.com/Avaiga/taipy-config/issues/69

- Make the _applied_config and the _default_config two different instances.
- Copy sections instead of re-using the same instance in the _Config._update method
- make the _config initializations consistent
- Create clear methods to clear the _applied_config before compilation.
- Unit tests

2023-05-29 04:06 UTC, trgiangdo requested changes
Thank you for your Pull Request. This is a severe bug and we are so happy that you found out and propose to fix it.

For the code change, I have some concerns. Please address these.
1. I don't see the purpose of the `clear()` method. The `_applied_config` and the `_default_config` are already 2 different instances (since `_Config._default_config()` returns a different `_Config` instance each call). Your change on copy section and unique_section when updating seems enough. Please clarify this for us.
2. The PR contains several commits of your previous PR, which will be merge soon. Before merging this PR, please rebase the branch with develop. And next time, can you use a fresh branch from develop? It will make it much easier for us to review. Thank you.

2023-05-29 09:53 UTC, jrobinAV requested changes

2023-05-29 09:53 UTC, jrobinAV commented on src/taipy/config/_config.py
> +                section.clear()
I prefer the name `clean` as it does not make the _config empty, but it cleans all the elements.
Plus, can you make it hidden?

```suggestion
    def _clean(self):
        self._global_config._clean()
        for unique_section in self._unique_sections.values():
            unique_section._clean()
        for sections in self._sections.values():
            for section in sections.values():
                section._clean()
```

2023-05-29 09:53 UTC, jrobinAV commented on src/taipy/config/config.py
> +        cls._applied_config.clear()
```suggestion
        cls._applied_config._clean()
```

2023-05-29 09:53 UTC, jrobinAV commented on src/taipy/config/global_app/global_app_config.py
> +    def clear(self):
```suggestion
    def _clean(self):
```

2023-05-29 09:53 UTC, jrobinAV commented on src/taipy/config/section.py
> +    def clear(self):
```suggestion
    def _clean(self):
```

2023-05-29 09:53 UTC, jrobinAV commented on tests/config/utils/section_for_tests.py
> +    def clear(self):
```suggestion
    def _clean(self):
```

2023-05-29 09:53 UTC, jrobinAV commented on tests/config/utils/unique_section_for_tests.py
> +    def clear(self):
```suggestion
    def _clean(self):
```

2023-05-29 10:14 UTC, bobbyshermi commented
> Thank you for your Pull Request. This is a severe bug and we are so happy that you found out and propose to fix it.
> 
> For the code change, I have some concerns. Please address these.
> 
> 1. I don't see the purpose of the `clear()` method. The `_applied_config` and the `_default_config` are already 2 different instances (since `_Config._default_config()` returns a different `_Config` instance each call). Your change on copy section and unique_section when updating seems enough. Please clarify this for us.
> 2. The PR contains several commits of your previous PR, which will be merge soon. Before merging this PR, please rebase the branch with develop. And next time, can you use a fresh branch from develop? It will make it much easier for us to review. Thank you.

Hello, 

1- `_clean` is used to keep all sections inside `_applied_config` the same instances between two compilations. Otherwise, some tests are failing because at the registration time you do expose `_applied_config._sections['name']` as an attribute. So If the instance changes, the attribute is not dynamically updated and still points to the old instance which can be out of date.

2- I believe the merge of my previous PR solved the issue. I will branch from Avaiga:develop branch next time. Thx.

Thank you for the review.

2023-05-29 10:17 UTC, jrobinAV approved these changes
Thx for the update.

2023-05-29 10:21 UTC, trgiangdo commented
> `_clean` is used to keep all sections inside `_applied_config` the same instances between two compilations

That's great. I would love to have a more generic way to implement the `_clear` method for all sections. But for now, this will do.

Can you also do a PR on taipy-core to propagate the `_clear()` method to other sections and unique sections?

2023-05-29 10:34 UTC, bobbyshermi commented
> > `_clean` is used to keep all sections inside `_applied_config` the same instances between two compilations
> 
> That's great. I would love to have a more generic way to implement the `_clear` method for all sections. But for now, this will do.
> 
> Can you also do a PR on taipy-core to propagate the `_clear()` method to other sections and unique sections?

I can propagate the changes if you want, but I won't have time this week. I mostly have time to work on taipy on the week-ends.

Thx,

2023-05-29 10:39 UTC, trgiangdo commented
Then I propose we delay the merge of this PR, since it will cause failing tests in other Taipy repositories.

In the meantime, we will investigate a more generic way to clear the `_applied_config`.
Thanks for your contribution 🫶

2023-06-01 03:22 UTC, trgiangdo commented
I just re-reviewed this PR and I have 1 more remark.

Essentially, the `_Config._clean()` method will reset all attributes of all sections and unique_sections to some sort of default value (like the SectionForTest).
And when compiling the `_applied_config`, these sections and unique_sections are replaced by instances in _default_config and _python_config anyway.

So, maybe instead of clean each one, we just remove these sections and unique_sections from the dictionary when calling `_clean()`?
Then we will be able to avoid the need for propagate the `_clean()` method to all sections, which will be hard to maintain.

@jrobinAV @bobbyshermi let me know your thoughts about this. Thank you

2023-06-01 16:29 UTC, jrobinAV commented
@trgiangdo I believe it does not work to remove sections since before and after the compilation the instances must be the same.

2023-06-01 23:40 UTC, trgiangdo commented
When we compile the config, we remove those anyway (by replacing it with copies of sections and unique_sections from _default_config), no?

2023-06-01 23:50 UTC, jrobinAV commented
Not really... We update each attribute one by one. The purpose is to have the following behavior:
```
config_1 = Config.configure_data_node("foo", "bar")
config_2 = Config.configure_data_node("foo", "baz")
assert config_1 is config_2
```
In the first line, config_1 references `Config._applied_config._sections["foo"]`.
Then before configuring `config_2` we clean the `_applied_config`.
Then in the second line, we make config_2 also a reference of `Config._applied_config._sections["foo"]`.
Since we want `config_1` and `config_2` to be the same instance, we must update the attributes, but not the instance itself.

I don't know if I am clear.

2023-06-08 04:25 UTC, trgiangdo approved these changes
The `_clean()` method has been propagated to all other Section and UniqueSection children.
This PR is ready to be merged.

2023-06-08 04:25 UTC, trgiangdo approved these changes
The `_clean()` method has been propagated to all other Section and UniqueSection children.
This PR is ready to be merged.

2023-06-08 07:46 UTC, merged